# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4faea4ab1a7557dbcf7ac339770d80f01e67a50be50e68b80d6bd9eec98fb1b7529a8fde32918280a6aaa196d58309e6630982b4464ed025c13aac2e52c9c11

test:
  secret_key_base: eab52d61898f7a0376deec732b432bb18133ab445b3e92e728767dd4c6ad3c7997d38e92f02b4536fe94bf5c1bee55f9656769839e87e3bd2271dcf72a78c059

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
